#!/usr/bin/env bash
# if the number of items in donwload doesnt change every 15 seconds
# then it may be hanging -- ping me

getCount() {
	find ./download | wc -l
}

lastCount=$(getCount)
sleep 15
while true; do
	newCount=$(getCount)
	if [[ "$newCount" != "$lastCount" ]]; then
		echo "count changed $lastCount -> $newCount"
		lastCount=$newCount
		sleep 15
	else
		# play a sound so I can check on it
		paplay /usr/share/sounds/freedesktop/stereo/message.oga
	fi
done
